name: Deploy (CVM Pull Mode & Git Pages Redirect)

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: true

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install & Build 项目
              run: |
                  npm install
                  cd vue-TelemetryInstruments && npm install && cd ..
                  npm run build

            #把编译好的静态网页，推送到当前仓库的 dist 分支
            - name: Push Assets to Dist Branch
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: dist-preview # 编译产物目录
                  branch: dist # 专门存放打包后文件的分支（会自动创建）
                  token: ${{ secrets.GITHUB_TOKEN }} # 无需配置，GitHub 自动生成

            - name: Trigger hook
              run: |
                  curl -k -s -X POST "${{ secrets.HOOK_URL }}" > /dev/null 2>&1

    deploy_redirect_to_pages:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4 # 必须 checkout，才能拿到 .github 下的文件

            # 如果 .github/page 下只有 index.html，需要生成一份 404.html
            - name: Prepare Redirect Files
              run: |
                  mkdir -p page
                  cp .github/page/index.html page/index.html
                  cp .github/page/index.html page/404.html

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: page # 上传处理后的目录

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
